.TH MSCRIPT 1 "23 Jul 2013"
.SH NAME
mscript \- Example of groff.
.SH SYNOPSIS
\fBmscript\fP [ -h | -b ] [ -f \fIfilename\fP ]
.SH DESCRIPTION
\fBmscript\fP is the swiss army knife of the scripts. 
It runs in the background monitoring activity in \fBfilename\fR. 

Paragraphs need an empty line before.
.SH OPTIONS
.TP
\fB-h\fP
Help, print out the command syntax.

.TP
\fB-b\fP
Background mode, the script daemonizes itself.
.TP
\fB-f\fR filename
The filename to be monitored for activity.
\fIfilename\fP shall include the full pathname.
.SH AUTHOR
Written by Me Myself.
.SH COPYRIGHT
Copyright 2012-2013 Me Myself.

This is free software; see the source for copying conditions.  There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH FILES
.TP
\fC/usr/bin/mscript\fR
.SH "SEE ALSO"
bash(5), python(5), groff(1)
.SH BUGS
No bugs had been reported. 
