
set nocompatible
filetype off
"
" """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" """ Install bundle
" """ git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
" """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"
" """ " set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
"
Plugin 'VundleVim/Vundle.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
"
Plugin 'junegunn/fzf'
Plugin 'junegunn/fzf.vim'
" Plugin 'terryma/vim-multiple-cursors'
Plugin 'tpope/vim-surround'
Plugin 'scrooloose/nerdtree'
Plugin 'ericcurtin/CurtineIncSw.vim'
" Plugin 'w0rp/ale'
" "Plugin 'zxqfl/tabnine-vim'
"
call vundle#end()            " required


" filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
" filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
"
"
"

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                              CSCOPE
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" mkdir ~/.vim/plugins
" cd ~/.vim/plugins
" wget http://cscope.sourceforge.net/cscope_maps.vim
"
"     Ctrl+]  for jumping to definitions
"     Ctrl+\ s (or Ctrl+Spacebar s)
"
"source ~/.vim/plugins/cscope_maps.vim


""""""""""""""""""""""""""
" Space and tab management
""""""""""""""""""""""""""
filetype plugin indent on
" disable vi compatibility (emulation of old bugs)
set nocompatible
" use indentation of previous line
set autoindent
" use intelligent indentation for C
" set smartindent
" set smarttab
set tabstop=4       " tab width is 4 spaces
set shiftwidth=4    " indent also with 4 spaces
set softtabstop=4   "
set expandtab       " expand tabs to spaces
"set diffopt+=iwhite
set nowrap
set ic

""""""""""""""""""""""
" Search
""""""""""""""""""""""
set incsearch    " incremental search
set hlsearch     " Hihghligth all searchs
set showmatch   " Always display the () matching

""""""""""""""""""""""
" Colors
""""""""""""""""""""""
set t_Co=256
syntax on

set background=dark
colorscheme elflord
set cursorline


" turn line numbers on
" set number
" intelligent comments
set comments=sl:/*,mb:\ *,elx:\ */


""""""""""""""""""""""
" Optimizations
""""""""""""""""""""""
set wildmenu    " Display autocomplete if possible
set lazyredraw  " speed up macros, avoiding redraw if possible



"""""""""""""""""""""""
" Folding
""""""""""""""""""""""""""
set foldenable          " enable folding
set foldlevelstart=10   " open most folds by default
set foldnestmax=10      " 10 nested fold max
"nnoremap <space> za     " space open/closes folds

""""""""""""""""""""""""""""""""""
" Keymaps to improve productivity
""""""""""""""""""""""""""""""""""
map <F12> :qa<CR>
map <F10> :make -f Makefile.mk<CR>
map <F9> :make FAST=1 -j <CR>
"map <F9> :make FAST=1 -j8 CLANG=1 AddressSanitizer=1 <CR>
map ; :Files<CR>
map <C-o> :NERDTreeToggle<CR>


""""""""""""""""""""""""""""""""""
" YouCompleteMe
"""""""""""""""""""""""""""""""""
" let g:ycm_use_clangd = 0


"""""""""""""""""""""""""""""""""
" ALE
""""""""""""""""""""""""""""""""
" let b:ale_linters = ['pyflakes', 'flake8', 'pylint']
" let b:ale_linters = ['flake8']
" let g:ale_python_flake8_args="--ignore=E221"

" ----------------------------------------------------------------------------------------
" Asynchronous Lint Engine
" ----------------------------------------------------------------------------------------
"let g:ale_linters = { 'python': ['flake8', 'pep8', 'vulture'], }
" let b:ale_linters = ['flake8']
" let g:ale_fixers = {'python': ['add_blank_lines_for_python_control_statements', 'autopep8', 'isort', 'yapf', 'remove_trailing_lines', 'trim_whitespace']}
" let g:ale_python_flake8_executable = 'python3'
" let g:ale_python_flake8_options    = '-m flake8 --ignore=E221,E265,E266,E501,E241'
" let g:ale_python_pep8_options      = '--max-line-length=100 --ignore=E221,E265,E266,E501'
" let g:ale_set_loclist              = 1
" let g:ale_set_quickfix             = 0


""""""""""""""""""""""""""""""""""
" Keymaps to improve productivity
""""""""""""""""""""""""""""""""""
map <C-K><C-O> :call CurtineIncSw()<CR>
